apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress-mysql
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  ports:
  - port: 3306
  selector:
    {{- include "wordpress.mysql.labels" . | indent 4 }}
  clusterIP: None
---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ .Release.Name }}-wordpress-mysql
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  serviceName: wordpress-mysql-statefulset
  selector:
    matchLabels:
      {{- include "wordpress.mysql.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.mysql.labels" . | indent 8 }}
    spec:
      containers:
      - name: mysql
        image: mysql@sha256:06c614dfc9720ccc0177acf700d0e0794f0efe3a032e78ea5318c30886ce62c1
        ports:
        - name: mysql
          containerPort: 3306
        env:
        - name: MYSQL_DATABASE
          value: wordpress
        - name: MYSQL_USER
          value: {{ .Values.db.username }}
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-password
              key: root
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: {{ .Release.Name }}-mysql-password
              key: wordpress
        volumeMounts:
        - name: {{ .Release.Name }}-mysql-pv-claim
          mountPath: /var/lib/mysql
  volumeClaimTemplates:
  - metadata:
      name: {{ .Release.Name }}-mysql-pv-claim
      labels:
        {{- include "wordpress.labels" . | indent 8 }}
    spec:
      accessModes:
      - ReadWriteOnce
      resources:
        requests:
          storage: 20Gi

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-mysql-password
data:
  root: {{ .Values.db.root_password | b64enc | quote }}
  wordpress: {{ .Values.db.password | b64enc | quote }}
