apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
  selector:
    {{- include "wordpress.frontend.labels" . | indent 4 }}

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-wordpress-ingress
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-wordpress
                port:
                  number: 80

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-wp-pv-claim
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wordpress.frontend.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.frontend.labels" . | indent 8 }}
    spec:
      containers:
        - name: wordpress
          image: wordpress:6.0.0
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-wordpress-mysql
            - name: WORDPRESS_DB_USER
              value: {{ .Values.db.username }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-password
                  key: wordpress
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wp-pv-claim
