apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      {{- include "wordpress.frontend.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "wordpress.frontend.labels" . | indent 8 }}
    spec:
      containers:
        - name: wordpress
          image: {{ .Values.wordpress.image | quote }}
          ports:
            - name: http
              containerPort: 80
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html
          env:
            - name: WORDPRESS_DB_HOST
              value: {{ .Release.Name }}-wordpress-mysql
            - name: WORDPRESS_DB_USER
              value: {{ .Values.db.username }}
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-mysql-password
                  key: wordpress
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: {{ .Release.Name }}-wp-pv-claim
