apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-wordpress
  labels:
    {{- include "wordpress.labels" . | indent 4 }}
spec:
  ports:
    - name: http
      port: 80
  selector:
    {{- include "wordpress.frontend.labels" . | indent 4 }}
